planning_scope: harness
profile: development.standard
protocol: adp/1
protocols: git+ssh://git@github.com/beyond10x/engineering-protocols.git#6d772015790a2917be404f14c35bf20fd6f83bdb
store:
  git: {}
version: aep.project/5
